### ISSUE TITLE
Is there a way to generate an erb tag around a selected text

### ISSUE THREAD

**Issue by gtarsia** [whatyouhide/vim-textobj-erb#4]
As in: Selecting `'stuff', pressing a keymap and getting `<%= 'stuff' %>`

Maybe this is out of topic.  
Thanks for reading.

**Comment by whatyouhide** [comment]
There is no way to generate a tag around a selection. I think it's out of scope of this plugin as this plugin just provides a text object for inside/around erb tags (so the erb tag is supposed to be there already).

Thanks for the report though!
